PNP_DUAL_FR3:
  robot_types: "['fr3v2','fr3v2']"
  arm_prefixes: "['left','right']"
  robot_ips: "['172.16.0.3','172.16.1.2']"
  load_gripper: "false"
  use_fake_hardware: "false"
  fake_sensor_commands: "false"
  joint_state_rate: 1000
  namespace: ""
  use_rviz: "true"
  thread_priority: 50
